\# BACKGROUND
background {
    monitor = DP-2
    path = screenshot
    blur_passes = 4
    blur_size = 7
    color = rgb(0, 0, 0)
}

# GENERAL
general {
    ignore_empty_input = true
    hide_cursor = false
}

# DATE
label {
    monitor = DP-2
    text = cmd[update:3600000] echo "$(date +"%A, %B %d")"
    color = rgba(242, 243, 244, 0.75)
    font_size = 25
    font_family = Google Sans Flex Bold
    position = 0, 320
    halign = center
    valign = center
}

# TIME
label {
    monitor = DP-2
    text = cmd[update:1000] echo "$(date +"%-I:%M %P")"
    color = rgba(242, 243, 244, 0.75)
    font_size = 100
    # Uses the maximum weight available in the variable axis
    font_family = Google Sans Flex Black
    position = 0, 200
    halign = center
    valign = center
}

# Profile Picture
image {
    monitor = DP-2
    path = /home/nick/.face
    size = 200
    border_size = 2
    border_color = rgb(255, 255, 255)
    position = 0, 0
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor = DP-2
    size = 400, 75
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.4
    dots_center = true
    outer_color = rgba(160, 160, 160, 0.22)
    inner_color = rgba(36, 36, 36, 0.42)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 12
    check_color = rgb(204, 136, 34)
    fail_color = rgb(255, 228, 50)
    capslock_color = rgb(255, 228, 50)
    placeholder_text = 
    hide_input = false
    position = 0, -170
    halign = center
    valign = center
}

# CAPS LOCK
label {
    monitor = DP-2
    text = cmd[update:100] grep -q "1" /sys/class/leds/input*::capslock/brightness && echo "󰪛  Caps Lock is ON"
    color = rgb(255, 228, 50)
    font_size = 16
    font_family = Google Sans Flex Bold
    position = 0, -230
    halign = center
    valign = center
}