general {
    lock_cmd = qs ipc -c Synoptik call lockscreen lock
    before_sleep_cmd = qs ipc -c Synoptik call lockscreen lock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_dbus_inhibit = true
    ignore_systemd_inhibit = true
}

# 1. Screensaver (2.5 minutes)
listener {
    timeout = 150
    on-timeout = qs ipc -c Synoptik call screensaver start
    on-resume = qs ipc -c Synoptik call screensaver stop
}

# 2. Session Lockscreen (5 minutes)
listener {
    timeout = 300
    on-timeout = qs ipc -c Synoptik call screensaver stop; qs ipc -c Synoptik call lockscreen lock
}

# 3. Display Off / DPMS (7 minutes)
listener {
    timeout = 420
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_inhibit = true
}